SELECT * FROM mariadb_prac1.flipkart;
use mariadb_prac1;
desc mariadb_prac1.flipkart;
select * , ROW_NUMBER() over() as num_row from mariadb_prac1.flipkart;
alter table flipkart add row_no int not null auto_increment primary key;
Select * from flipkart where (row_no=5 or row_no=10 or row_no = 15  or row_no =20);
select `Order Priority`,Sales,Discount from flipkart where (row_no=5 or row_no=10 or row_no = 15  or row_no =20);
create table dbs(empid int NOT NULL, empname varchar(20) NOT NULL,empaddr varchar(20) NOT NULL,primary key(empid));
select * from flipkart where `Customer Name` regexp 'b';
alter table flipkart modify column `Customer Name` varchar(20) COLLATE SQL_Latin1_General_CP1_CS_AS ;
select * from flipkart where BINARY `Customer Name`regexp 'b';
select * from flipkart where `Customer Name` like 'A%' and `Ship Mode`="Express Air" and `Sales` between 100 and 150;
select `Ship Mode`,sum(`Shipping Cost`) as `Shpping cost` from flipkart group by `Ship Mode`;
select `Product Category`,max(`Shipping Cost`),min(`Shipping Cost`) from flipkart group by `Product Category`;
create table paytm as select `Customer Name`,sales from flipkart;
select distinct `Order Priority` from flipkart;
select `Product container`,count(`Product container` ) from flipkart group by `Product Container`;
select count(distinct `Product Container`) from flipkart;
select region,sum(discount), sum(`shipping cost`) from flipkart  group by region;
select `Customer Name` from flipkart where `Customer Name` regexp '^[aeiou]';
select `product sub-category` ,min(`Shipping cost`) from flipkart group by `product sub-category`; 
select max(discount), `product sub-category` from flipkart group by `product sub-category`;
select `product name` from flipkart where `product name` regexp '[0-9]';
select region,`order priority` ,if(sum(Sales)>50000,'Yes','No') as result from flipkart  ; 
select `ship mode`,case `ship mode` when 'Express Air' then 'ea' when 'Delivery Air' then 'da' else 'ra' end as details from flipkart;
SELECT * FROM mariadb_prac1.dbs;
insert into dbs values(1,"likhitha","hyd");
alter table dbs add subject varchar(10);
desc dbs;
update  dbs  set subject="mariadb" where empid=1;
select `Order Priority`,avg(Sales) as avgsales from flipkart;
desc flipkart;
select `Customer Name`,Sales from flipkart order by Sales desc limit 5;
select region,count(`Product Category`) from flipkart group by `Product Category`;
select `Customer Name`, max(Discount) from flipkart group by `Customer Name` order by Discount desc limit 1;
select * from flipkart where `Customer Name`="David Hoyle";
select max(Discount) from flipkart;
use mariadb_prac1;
SELECT * FROM mariadb_prac1.sampledataforgb;
select `Name`, max(Salary) from sampledataforgb group by `Name` order by Salary desc ;
select max(Salary) from sampledataforgb;
ALTER TABLE `mariadb_prac1`.`sampledataforgb (1)` RENAME TO  `mariadb_prac1`.`sampledata` ;
SELECT id, fname, lname FROM sampledata WHERE class = 'python'; 
Explain SELECT id, fname, lname FROM sampledata WHERE class = 'python';  
CREATE INDEX class ON sampledata (class);
Explain sELECT id, fname, lname FROM sampledata WHERE class = 'python'; 
SHOW INDEXES FROM sampledata; 
use mariadb_prac1;
SELECT * FROM mariadb_prac1.dbsdata;
select job,loan from dbsdata where age>50 and marital="married" ;
select distinct job from dbsdata;
select education from dbsdata group by education order by marital desc ;
select marital,count(marital) as count  from dbsdata group by marital;
select education,avg(pdays)from dbsdata group by education;
select max(duration),min(pdays),age from dbsdata where age>60 group by age order by age desc;
select count(distinct age) from dbsdata;
select distinct age from dbsdata;
select education from dbsdata where housing="no" or loan="yes" group by marital;
select job from dbsdata where education regexp "[0-9]" group by job;


